logger:
  prefix: 'leaps'
  log_level: INFO
  add_timestamp: true
stats:
  prefix: leaps
riemann:
  address: localhost:5555
storage:
  type: mock
  name: test_document
authenticator:
  type: none
  allow_creation: true
http_server:
  static_path: /
  socket_path: /socket
  address: :8001
  www_dir: ../static/example
admin_server:
  static_path: /
  path: /
  address: localhost:4040
  www_dir: ../static/stats
